<? $this->headScript()->prependFile($this->getJs('login.js', 'user')); ?>
<? $this->headLink()->appendStylesheet($this->getStyle('login.css', 'user'), 'screen') ?>

<div class="flips-wrappers cf">

	<div id="flip-login-form" class="form-bg flip-form active">
	
		<div class="login-left">
			<h1 class="logo">One Parish</h1>
			<h3>Catholic. Connected. Community.</h3>
		</div>
		<!--flip-login-left-->
		
		<div class="flip-login-right">
		
			<div class="loginHolder">

				<div class="loginBox">
					
					<div class="loginBoxHeader"><h4 class="text-caps"><?= $this->translate('Sign In. Get Started') ?></h4></div>
					<form class="userLogin" action="<?= $this->links('login') ?>" method="post">
						<div>
							<p id="showLoginError" class="alert alert-danger hide">Username or password does not match.</p>
						</div>
						<div class="boxContent">
							<fieldset>
								<div class="input-prepend">
									<input type="text" required="" size="16" name="email" id="email" class="medium form-control top-input" value="" placeholder="Enter your username" />
								</div>
								<div class="input-prepend">
									<input type="password" required="" size="16" name="password" id="password" class="medium form-control" value="" placeholder="Password" />
								</div>
							</fieldset>
						</div>
						<div class="actions">
							<button type="submit" class="button button-long button-yellow"><?= $this->translate('SIGN IN') ?></button>
						</div>
					</form>
					
				</div>
				<!--loginBox-->
				
				<div class="user-resets">
					<a id="forgot-passwd-link" class="grey-link" href="#recover_password">Forgot your password?</a>
                </div>
				<!--user-resets-->
				
				<div class="divider">
					<h5>OR</h5>
              	</div>
				<!--divider-->
				
				<div class="sign-up text-centered">
					<a id="new-account-link" class="button button-long button-blue toggle-trigger" href="#">Create an Account</a>
              	</div>
				<!--sign-up-->
				
			</div>
			<!--loginHolder-->
			
		</div>
		<!--flip-login-right-->
		
	</div>
	<!--flip-login-form-->
	
	<div id="sign-up-form" class="form-bg flip-form">
		
		<div class="form-header">
            <h2>Create An Account</h2>
        </div>
		<!--form-header-->
		<div class="flash_message hide" style="">
			<p class="alert"></p>
		</div>
		<form class="sign-up-form agile" action="<?= $this->links("register") ?>" method="post">
			<div class="row bottom-margin-30">
				<div class="span5">
					<label>First Name</label>
				<input type="text" required="" placeholder="John" class="form-control input-width" name="firstName">
				</div>
				<div class="span5">
					<label>Last Name</label>
				<input type="text" required="" placeholder="Baker" class="form-control input-width" name="lastName">
				</div>
			</div>
			<div class="row bottom-margin-30">
				<div class="span5">
					<label>Email Address</label>
				<input type="email" required="" placeholder="John-Baker@oneparish.com" class="form-control input-width" name="email">
				</div>
				<div class="span5">
					<label>Create Password</label>
				<input type="password" required="" placeholder="•••••••••" class="form-control input-width" name="password" value="">
				</div>
			</div>
			<div class="row bottom-margin-15">
		  <div class="sign-up-terms">
			<label>Terms of Service &amp; Privacy Policy</label>
			<label class="checkbox">
			  <input type="checkbox" required="" name="acceptedAgreements" id="agreements_checkbox">Yes, I agree to the <a class="orange-link" href="#">Terms of Serivce</a> and <a class="orange-link" href="#">Privacy Policy</a>.
			</label>
		  </div>
			</div>
			<div class="form-button-group">
				<a id="sign-up-cancel" class="toggle-trigger grey-link right-margin-20" href="#">Cancel Sign Up</a>
				<input type="Submit" class="button button-yellow" value="Create Account">
			</div>
			<div class="form-button-group loader-here hide">
				<div id="floatingCirclesG" class="loading-delete-families"><div id="frotateG_01" class="f_circleG"></div><div id="frotateG_02" class="f_circleG"></div><div id="frotateG_03" class="f_circleG"></div><div id="frotateG_04" class="f_circleG"></div><div id="frotateG_05" class="f_circleG"></div><div id="frotateG_06" class="f_circleG"></div><div id="frotateG_07" class="f_circleG"></div><div id="frotateG_08" class="f_circleG"></div></div>
			</div>
		</form>
		
	</div>
	<!--#sign-up-form-->
	
	<div id="forgot-passwd" class="form-bg flip-form forgot-passwd">
		
		<div class="form-header">
            <h2>Need help logging in?</h2>
        </div>
		<!--form-header-->
		<div class="flash_message hide" style="">
			<p class="alert"></p>
		</div>
		<!--flash_message-->
		<form class="text-centered recover-form agile" id="recover_password" method="post" action="<?= $this->links('forgot_password') ?>">
			<i class="dripicon-lock user-recovery-icon"></i>
			<h3>Need help recovering your password?</h3>
			<div class="form-group">
				<input type="email" required="" autofocus="true" placeholder="Enter your email for this account." name="email">
				<input id="recover-submit" type="submit" class="button button-yellow" value="submit">
			</div>
		</form>
		<div class="form-shared-links text-centered">
			<a id="cancel-passwd" class="grey-link" href="#">Cancel And Return To Sign In Page</a>
        </div>
				
	</div>
	<!--forgot-passwd-->

</div>
<!--flips-wrappers-->