<? $this->headScript()->prependFile($this->getJs('login.js', 'user')); ?>
<? $this->headLink()->appendStylesheet($this->getStyle('login.css', 'user'), 'screen') ?>

<div class="flips-wrappers cf">

	<div id="forgot-passwd" class="form-bg forgot-passwd">
		
		<div class="form-header">
            <h2>Parish required</h2>
        </div>
		<!--form-header-->
		<div class="flash_message hide" style="">
			<p class="alert"></p>
		</div>
		<!--flash_message-->
		<form class="text-centered recover-form agile" id="recover_password" method="post" action="<?= $this->links('forgot_password') ?>">
			<i class="dripicon-lock user-recovery-icon"></i>
			<h3>
				It seems that you do not have a parish assigned to your user.
				<br />
				In order to have a parish assigned and access your parish directory, <br />please contact <a href="http://oneparish.com">oneParish.com</a>.
			</h3>
		</form>
		<div class="form-shared-links text-centered">
			<a class="grey-link" href="/logout">Return To Sign In Page</a>
        </div>
				
	</div>
	<!--forgot-passwd-->

</div>
<!--flips-wrappers-->