<section class="app-page-header">
  <div class="row-fluid">
    <div class="span9">
      <h2>Family Details</h2>
    </div>
  </div>
</section>
<div class="app-body-content family-details-content">
	<form class="edit-family agile" action="" method="post" url="Mircea">
	    <section>
	  		<div class="row-fluid">
		        <div class="span7">
		          <h4 class="subhead"> <a href="#parish_directory"><i class="fa fa-arrow-left"></i></a> <?= isset($this->family['lastName']) ? $this->family['lastName'] : '' ?>'s Information</h4>
		        </div>
		        <div class="span5">
			        <p class="family-code text-caps pull-right">
			           <i class="dripicon-question tool-tip" data-original-title="The family access code is used to let family members join an existing family." title="" data-toggle="tooltip" id="help-tooltip"></i> Family Access Code: 
			           <input type="text" class="small-input" placeholder="123456" name="accessCode" value="<?= isset($this->family['accessCode']) ? $this->family['accessCode'] : '' ?>">
			        </p>
		        </div>
	  		</div>
	  	</section>
	    <section class="detail-section family-details">
		    <div class="row-fluid">      
		        <div class="span4">
		         	<div class="family-img">
		            	<img src="<?= isset($this->family['familyPhoto']['url']) ? $this->family['familyPhoto']['url'] : 'http://placehold.it/350x350' ?>">            
		          	</div>
		          	<input type="file" name="familyPhoto" id="family_photo">
		          	<label class="horizontal-form-label top-margin-10">
		            	<input type="checkbox" value="true" class="public-profile" name="publicProfile">
		            	Public Profile
		          	</label>
		        </div>
		        <div class="span7 offset1">
		        	<div class="row">
						<div class="span6">
							<label>First Name</label>
							<input type="text" class="half-input" value="<?= isset($this->family['firstName']) ? $this->family['firstName'] : '' ?>" placeholder="First Name" name="firstName">
						</div>
						<div class="span6">
							<label>Last Name</label>
							<input type="text" class="half-input" value="<?= isset($this->family['lastName']) ? $this->family['lastName'] : '' ?>" placeholder="Last Name" name="lastName">
						</div>
					</div>
					<div class="row">
						<div class="span12">
							<label>Street Address</label>
							<input type="text" class="full-input" value="<?= isset($this->family['addressLine1']) ? $this->family['addressLine1'] : '' ?>" placeholder="Street Address" name="addressLine1">
						</div>
					</div>
					<div class="row">
						<div class="span5">
							<label>City</label>
							<input type="text" class="half-input" value="<?= isset($this->family['addressCity']) ? $this->family['addressCity'] : '' ?>" placeholder="City" name="addressCity">
						</div>
						<div class="span2">
							<label>State</label>
							<input type="text" class="small-input" value="<?= isset($this->family['addressState']) ? $this->family['addressState'] : '' ?>" placeholder="State" name="addressState">
						</div>
						<div class="span5">
							<label>Zip Code</label>
							<input type="text" class="half-input" value="<?= isset($this->family['addressZip']) ? $this->family['addressZip'] : '' ?>" placeholder="Zipcode" name="addressZip">
						</div>
					</div>
					<div class="row">
						<div class="span5">
							<label>Email Address</label>
							<input type="email" class="half-input" value="<?= isset($this->family['email']) ? $this->family['email'] : '' ?>" placeholder="Email Address" name="email">
						</div>
						<div class="span4">
							<label>Phone Number</label>
							<input type="text" class="half-input" value="<?= isset($this->family['phone']) ? $this->family['phone'] : '' ?>" placeholder=" Home phone number" name="phone">
						</div>
						<div class="span3">
							<label>Envelope #</label>
							<input type="text" class="half-input" value="<?= isset($this->family['envelopeNumber']) ? $this->family['envelopeNumber'] : '' ?>" placeholder="1001" name="envelopeNumber">
						</div>
					</div>
					<div class="form-group span12">
						<div class="pull-right">
							<input type="submit" name="save" class="button button-green pull-right" value="Save" />
						</div>
					</div>
		        </div>
		   	</div>
	    </section>
 	</form>
 	<section class="detail-section no-border-bottom">
   		<div class="row-fluid">
      		<div class="span9">
         		<h4 class="subhead">Members</h4>
      		</div>
      		<div class="pull-right">
        		<h4><a class="new-member" href="#">+ Add new</a></h4>
    		</div>
		    <div class="add-new-member">
		        <form class="edit-member form-horizontal agile" method="post" action="">
		  			<br>
				  	<div class="form-group span10">
				  		<div class="span3">
				  			<label class="horizontal-form-label">First Name</label>
				  		</div>
				  		<div class="span9">
					  		<input type="text" required="" value="" placeholder="John" class="horizontal-input" name="firstName">
				  		</div>
				  	</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Last Name</label>
		  				</div>
			  			<div class="span9">
		  					<input type="text" value="" placeholder="Baker" class="horizontal-input" name="lastName">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Birthday</label>
		  				</div>
		  				<div class="span9">
		  					<input type="date" value="" placeholder="mm/dd/yyyy" class="horizontal-input birthday" name="birthday">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Email</label>
		  				</div>
		  				<div class="span9">
		  					<input type="email" value="" placeholder="john@oneparish.com" class="horizontal-input" name="email">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Phone</label>
		  				</div>
		  				<div class="span9">
		  					<input type="text" value="" placeholder="(123) 456-7891" class="horizontal-input" name="phone">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Facebook</label>
		  				</div>
						<div class="span9">
		  					<input type="text" value="" placeholder="facebook.com/joe.catholic" class="horizontal-input" name="facebook">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Twitter</label>
		  				</div>
		  				<div class="span9">
		  					<input type="text" value="" placeholder="@joecatholic" class="horizontal-input" name="twitter">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label>Picture</label>
		  				</div>
		  				<div class="span9">
		  					<input type="file" name="picture" class="member_picture">
							<button type="submit" name="addNewMember" class="button button-green pull-right" value="save">Save</button>
		  				</div>
		  			</div>
				</form>
		    </div>
		    <!--add-new-member-->
    	</div>
	    <div class="row-fluid">
	    	<div class="span12">
	        	<dl class="family-member-container">
	        		<? foreach ($this->persons as $key => $person): ?>
		        		<dd data-member-id="<?= $person->objectId ?>" class="row-fluid family-member">
							<div class="span9">
								<ul>
									<li><img class="family-member-avatar" src="<?= isset($person->picture->url) ? $person->picture->url : 'http://f.cl.ly/items/2H211Q3s3W0k0q1R3i0m/default-avatar.png' ?>"></li><!--default avatar-->
									<li class="member-name"><?= $person->firstName .' '. $person->lastName ?></li>
								</ul>
							</div>
							<div class="span3 text-right edit-trigger">
								<a href="#"></a>
							</div>
							<!--edit-trigger-->
							<div class="span12 edit-member-form">
								<form class="edit-member form-horizontal">
								 	<br>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">First Name</label>
								  		</div>
								  		<div class="span9">
								  			<input type="text" required="" value="<?= $person->firstName ?>" placeholder="John" class="horizontal-input" name="firstName">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Last Name</label>
								  		</div>
								  		<div class="span9">
									  		<input type="text" value="<?= $person->lastName ?>" placeholder="Baker" class="horizontal-input" name="lastName">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Birthday</label>
								  		</div>
								  		<div class="span9">
									  		<input type="date" value="<?= date('m/d/Y', strtotime($person->birthday->iso)) ?>" placeholder="mm/dd/yyyy" class="horizontal-input birthday" name="birthday">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Email</label>
								  		</div>
								  		<div class="span9">
									  		<input type="email" value="<?= $person->email ?>" placeholder="john@oneparish.com" class="horizontal-input" name="email">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Phone</label>
								  		</div>
								  		<div class="span9">
									  		<input type="text" value="<?= $person->phone ?>" placeholder="(123) 456-7891" class="horizontal-input" name="phone">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Facebook</label>
								  		</div>
								  		<div class="span9">
								  			<input type="text" value="<?= $person->facebook ?>" placeholder="facebook.com/joe.catholic" class="horizontal-input" name="facebook">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
									  	<div class="span3">
								  			<label class="horizontal-form-label">Twitter</label>
								  		</div>
								  		<div class="span9">
								  			<input type="text" value="<?= $person->twitter ?>" placeholder="@joecatholic" class="horizontal-input" name="twitter">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
									  	<div class="span3">
									  		<label>Picture</label>
								  		</div>
								  		<div class="span9">
								  			<input type="file" name="picture" class="member_picture">
								      		<button class="button button-green pull-right">Save</button>
								      		<a class="member_destory button button-red pull-right right-margin-10" data-id="atbokmzf8G" href="#">Remove</a>
								  		</div>
								  	</div>
								</form>
							</div>
							<!--edit-member-form-->
						</dd>
					<? endforeach; ?>
	        	</dl>
	     	</div>
	    </div>
  	</section>
</div>
<!--app-body-content-->

<div class="alert alert-danger" style="display: none;">Oops. We were not able to save your information. Please try again.</div>

<script type="text/javascript">
  $(document).ready(function(){
  	VanillaZF.minister('body');
    $('#help-tooltip').tooltip();
    $('a.new-member').click(function(e) {
    	e.preventDefault();
    	$('.add-new-member').show();
    	return false;
    });
	$('a.member_destory').click(function() {
	   if (confirm('Are you sure you want to delete this family member?')) {
	      // do delete item
	      return false;
	   }
	});

	$('.edit-trigger').on( "click", function() {
		$(this).toggleClass("open");
		$(this).next('.edit-member-form').slideToggle();
		return false;
	});
  });
</script>