<section class="dashboard-header">
	<div class="row">
		<div class="span2">
			<img class="dashboard-parish-img" src="<?= $this->getImage('profile-default.png'); ?>">
		</div>
		<div class="span5 parish-information">
			<h2 class="parish-title">St. Columbkille</h2>
			<dl class="parish-details">
				<dd>Familes: 0</dd>
			</dl>
		</div>
	</div>
	<div class="row">
		<div class="offset2 span5 actions-row">
			<a href="<?= $this->links('parish_details') ?>"><small>Edit Parish Details</small></a>
		</div>
	</div>
</section>
<section class="app-body-content top-margin-30">
	<div class="row-fluid">
		
		<div class="span6 dashboard-container">
			<div class="container-header blue">
				<h4 class="container-header-title"> <i class="dripicon-calendar"></i> Upcoming Events</h4>
			</div>
			<div class="container-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th width="55%">Event Title</th>
							<th width="20%">Date</th>
							<th width="20%">Time</th>
						</tr>
					</thead>
					<tbody>
            
					</tbody>
				</table>
			</div>
			<div class="container-footer">
				<a href="#events">View All Events</a>
			</div>
		</div>
		<div class="span6 dashboard-container">
			<div class="container-header teal">
				<h4 class="container-header-title"> <i class="dripicon-user-group"></i> Newest Families</h4>
			</div>
			<div class="container-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th width="60%">Family's Name</th>
							<th width="30%">Added on</th>
							<th width="10%">Edit</th>
						</tr>
					</thead>
					<tbody>
            			<? foreach ($this->newFamilies as $key => $family): ?>
	  						<tr>
	  							<td><?= isset($family->firstName) ? $family->firstName : '' ?> <?= isset($family->lastName) ? $family->lastName : '' ?></td>
	  							<td><?= isset($family->createdAt) ? date('m/d/Y \a\t g:i A', strtotime($family->createdAt)) : '' ?></td>
	  							<td><a class="dripicon-document-edit" href="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>" onclick="makeTheCall('<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>', {}); return false;"></a></td>
	  						</tr>
	            
	  						<!--tr>
	  							<td>ctest, ctest</td>
	  							<td>5/8/2014 at 1:02 PM</td>
	  							<td><a class="dripicon-document-edit" href="#families/Z1k5onc9uc/edit"></a></td>
	  						</tr-->
            			<? endforeach; ?>
					</tbody>
				</table>
			</div>
			<div class="container-footer">
				<a href="#parish-directory">View Your Directory</a>
			</div>
		</div>

	</div>
</section>