<section class="app-page-header">
	<div class="row-fluid">
		<div class="span9">
			<h2>School Details</h2>
		</div>
	</div>
</section>
<div class="app-body-content">
	<section class="detial-section top-padding-30 bottom-padding-50">
		<div class="row-fluid">
			<form id="contact-forms" class="form-horizontal validate-me agile" method="post" action="">
				<h4 class="subhead">Basic Information</h4>

				<? if (isset($this->school['objectId']) && $this->school['objectId'] != ''): ?>
					<input type="hidden" name="objectId" value="<?= $this->school['objectId'] ?>">
				<? endif; ?>

				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">School Name</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['name']) ? $this->school['name'] : '' ?>" data-validation="FullNameValid" placeholder="Enter School's Name" class="horizontal-input" name="name">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Grade Levels</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['gradeLevels']) ? $this->school['gradeLevels'] : '' ?>" placeholder="" class="horizontal-input" name="gradeLevels">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Street Address</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['addressLine1']) ? $this->school['addressLine1'] : '' ?>" placeholder="" class="horizontal-input" name="addressLine1">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Address City</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['addressCity']) ? $this->school['addressCity'] : '' ?>" placeholder="" class="horizontal-input" name="addressCity">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">State</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['addressState']) ? $this->school['addressState'] : '' ?>" placeholder="" class="horizontal-input" name="addressState">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Zip</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['addressZip']) ? $this->school['addressZip'] : '' ?>" placeholder="" class="horizontal-input" name="addressZip">
					</div>
				</div>

        
				<div class="clearfix"></div>
				<h4 class="subhead top-padding-30">Contact Details</h4>
        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Contact Email</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['email']) ? $this->school['email'] : '' ?>" placeholder="" data-validation="email" data-validation-optional="true" class="horizontal-input" name="email">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Fax #</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['fax']) ? $this->school['fax'] : '' ?>" placeholder="" class="horizontal-input" name="fax">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Phone #</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['phone']) ? $this->school['phone'] : '' ?>" placeholder="" data-validation="PhoneNumberValid" data-validation-optional="true" class="horizontal-input" name="phone">
					</div>
				</div>

        
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Website</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->school['website']) ? $this->school['website'] : '' ?>" placeholder="" class="horizontal-input" name="website">
					</div>
				</div>

				<div class="form-group span12">
					<div class="span4 pull-right">
						<button class="button button-green pull-right">Save</button>
					</div>
				</div>
			</form>
		</div>
	</section>
</div>
<!--app-body-content-->
<div class="alert alert-success" style="display: none;"></div>
<script>

	$.formUtils.addValidator({
		name : 'FullNameValid',
		validatorFunction : function(value, $el, config, language, $form) {
			//var usernameRegex = '/^([a-zA-Z&]+)$/';
			return value.match(/^([a-zA-Z\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only characters.',
		errorMessageKey: 'badEvenNumber'
	}); 

	$.formUtils.addValidator({
		name : 'LastNameValid',
		validatorFunction : function(value, $el, config, language, $form) {
			return value.match(/^([a-zA-Z-\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only characters and -',
		errorMessageKey: 'badEvenNumber'
	});

	$.formUtils.addValidator({
		name : 'PhoneNumberValid',
		validatorFunction : function(value, $el, config, language, $form) {
			return value.match(/^([0-9-()\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only numbers and - or ( )',
		errorMessageKey: 'badEvenNumber'
	}); 

	$.validate({
	  form : '.validate-me'
	});

</script>