<section class="app-page-header">
	<h2>Add New Family</h2>
</section>
<!--page-content-header-->
<div class="app-body-content">
	<section class="detail-section no-border-bottom">
		<div class="row-fluid">
			<p class="top-margin-15">Fill out the form below to add families to your parish directory.</p>
			<form class="form-horizontal validate-me agile" method="post" action="">
				
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">First Name</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="John &amp; Marie" data-validation="FirstNameValid" data-validation-optional="false" class="horizontal-input" name="firstName">
					</div>
				</div>

				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Last Name</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="Ryan" data-validation="LastNameValid" class="horizontal-input" name="lastName">
					</div>
				</div>
					
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Street Address</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="123 Main St." class="horizontal-input" name="addressLine1">
					</div>
				</div>

				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">City</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="Chicago" class="horizontal-input" name="addressCity">
					</div>
				</div>

				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">State</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="IL" data-validation="length" data-validation-length="max2" class="horizontal-input" name="addressState">
					</div>
				</div>
		
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Zip</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="60614" class="horizontal-input" name="addressZip">
					</div>
				</div>

				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Phone</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="(123) 456-7891" data-validation="PhoneNumberValid" data-validation-optional="true" class="horizontal-input" name="phone">
					</div>
				</div>

				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Email</label>
					</div>
					<div class="span9">
						<input type="text" value="" placeholder="example@oneparish.com" data-validation="email" data-validation-optional="true" class="horizontal-input" name="email">
					</div>
				</div>

				<div class="form-group span12">
					<div class="span4 pull-right">
						<button class="button button-green pull-right">Save</button>
					</div>
				</div>
			</form>
			<!--form-->
		</div>
		<!--row-fluid-->
	</section>
	<!--detail-section-->
</div>
<!--app-body-content-->
<script>

	$.formUtils.addValidator({
		name : 'FirstNameValid',
		validatorFunction : function(value, $el, config, language, $form) {
			//var usernameRegex = '/^([a-zA-Z&]+)$/';
			return value.match(/^([a-zA-Z&\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only characters and &',
		errorMessageKey: 'badEvenNumber'
	}); 

	$.formUtils.addValidator({
		name : 'LastNameValid',
		validatorFunction : function(value, $el, config, language, $form) {
			return value.match(/^([a-zA-Z-\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only characters and -',
		errorMessageKey: 'badEvenNumber'
	});

	$.formUtils.addValidator({
		name : 'PhoneNumberValid',
		validatorFunction : function(value, $el, config, language, $form) {
			return value.match(/^([0-9-()\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only numbers and - or ( )',
		errorMessageKey: 'badEvenNumber'
	}); 

	$.validate({
	  form : '.validate-me'
	});

</script>
