<section class="app-page-header">
	<div class="row-fluid">
		<div class="span8">
	  		<h2>Aprove New Families</h2>
	  	</div>
	    <dl class="family-search">
	      <dd>
	      	<form class="family-search-form agile" action="">
	        	<input name="search" type="text" class="search-input search-family" value="<?= isset($this->search) ? $this->search : '' ?>" placeholder="Search By Last Name" id="directory_search">
				<div id="floatingCirclesG" class="hide">
					<div class="f_circleG" id="frotateG_01"></div>
					<div class="f_circleG" id="frotateG_02"></div>
					<div class="f_circleG" id="frotateG_03"></div>
					<div class="f_circleG" id="frotateG_04"></div>
					<div class="f_circleG" id="frotateG_05"></div>
					<div class="f_circleG" id="frotateG_06"></div>
					<div class="f_circleG" id="frotateG_07"></div>
					<div class="f_circleG" id="frotateG_08"></div>
				</div>
				<!--circular loading-->
	        	<a class="search-trigger" href="#"><i class="dripicon-search"></i></a>
	        </form>
	      </dd>
	      <div id="suggestions-container" class="hide"></div>
	      <!--suggestions-container-->
	    </dl>
	</div>
</section>
<section class="app-body-content">
	<div class="row-fluid">
	    <div class="span12">    
			<div id="searchResults" class="hide">
				<br>
				<p class="top-margin-30"></p>
			</div>
	  		<table id="data-table" url="<?= $this->links('approve_familes') ?>" class="table table-striped table-hover directory_table families-table aprove-table">
				<thead class="table-headers">
					<tr>
						<th width="20%">
							  <a title="Desc" class="order desc" data-db-attr="lastName" href="?orderBy=lastName&orderType=Desc"></a>
							  <a title="Asc" class="order asc" data-db-attr="lastName" href="?orderBy=lastName&orderType=Asc"></a>
							  Last Name
						</th>
						<th width="20%">
							  <a title="Desc" class="order desc" data-db-attr="firstName" href="?orderBy=firstName&orderType=Desc"></a>
							  <a title="Asc" class="order asc" data-db-attr="firstName" href="?orderBy=firstName&orderType=Asc"></a>
							  First Name
						</th>
						<!--<th width="25%">Address</th>-->
						<th width="20%">Phone</th>
						<th width="20%">Email</th>
						<th width="20%">Action</th>
					</tr>
				</thead>  
				<tbody>
				  	<? if ($this->familiesCount > 0): ?>
					  	<? foreach ($this->families as $key => $family): ?>
							<tr url="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>">
								<td><a href="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>"><?= isset($family->lastName) ? $family->lastName : '' ?></a></td>
								<td><a href="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>"><?= isset($family->firstName) ? $family->firstName : '' ?></a></td>
								<td><?= isset($family->phone) ? $family->phone : '' ?></td>
								<td><a href="mailto:<?= isset($family->email) ? $family->email : '' ?>"><?= isset($family->email) ? $family->email : '' ?></a></td>
								<td><button data-id="<?= isset($family->objectId) ? $family->objectId : '' ?>" class="button button-green span6 approve">Approve</button>
									<button data-file="<?= isset($family->familyPhoto->name) ? $family->familyPhoto->name : '' ?>" data-id="<?= isset($family->objectId) ? $family->objectId : '' ?>" class="button button-red span6 no_approve">Delete</button></td>
						   	</tr>
					  	<? endforeach; ?>
				  	<? else: ?>
						<tr>
							<td colspan="6">There are no families that need approval.</td>
						</tr>
				  	<? endif; ?>
		</tbody>
			</table>
			<div class="pagination light-theme simple-pagination">
	      		<ul>
					<? if ($this->familiesCount > 0): ?>
						<?= $this->pagination->display() ?>
					<? endif; ?>
	      		</ul>
      		</div>
		</div>
		<!--span12-->
	</div>
	<!--row-fluid-->

</section>
<!--app-body-content-->
<script type="text/javascript">
	var approved_url = "<?= $this->links('approve_familes') ?>";
	var familydeleteURL = "<?= $this->links('family_delete', array('family_id' => 0)) ?>";
	$.getScript("<?= My_Core::getApplicationUri() . $this->getJs('approvefamilies.js', 'families') ?>");
</script>