<script src="<?= $this->getJs('editdirectory.js', 'families') ?>"></script>
<section class="app-page-header">
  <h2>Fix Duplicates</h2>
</section>
<div id="edit-directory" class="app-body-content">
	<section class="directory-edit-filters-container">
		<div class="row-fluid">
			<div class="span12">
				<nav>
					<ul>
						<li id="duplicate_number">
							Duplicate Families (<?= count($this->duplicateFamilies) ?>)
						</li>
						<li class="pull-right">
							Do you need to remove your entire directory? <a id="delete_parish_trigger" class="orange-link" href="#deleteParishModal">Delete directory...</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</section>
	<!--directory-edit-filters-container-->
	<div class="tab-container active" id="duplicates">
		<br>
		<? if (count($this->duplicateFamilies) > 0): ?>
			<p class="remove-duplicates-note">
			  Please review and select the listings you wish to remove.<strong>TIP:</strong> If there are two enteries for John Baker, select only one of the listsings and press remove.
			</p>
		<? endif; ?>
		<br>
		<div class="carousel slide" id="myCarousel" data-interval="false">
			<div class="carousel-inner">
			  	<? if (count($this->duplicateFamilies) > 0): ?>
					<? foreach ($this->duplicateFamilies as $key => $families): ?>
						<div class="item <?= $key == 0 ? 'active' : '' ?>">
							<table id="data-table" class="table table-striped table-hover directory_table families-table fix_duplicates_table">
								<thead class="table-headers">
									<tr>
										<th width="20%">
											Last Name
										</th>
										<th width="20%">
											First Name
										</th>
										<th width="20%">Address</th>
										<th width="10%">Phone</th>
										<th width="20%">Email</th>
										<th width="10%"></th>
									</tr>
								</thead>  
								<tbody>
									<? foreach ($families as $key => $family): ?>
										<tr data-id="<?= $family['objectId'] ?>" url="<?= $this->links('family_details', array('family_id' => $family['objectId'])) ?>">
											<!--
												<td><input type="checkbox" class="delete_selection" data-href="<?= $this->links('family_delete', array('family_id' => $family['objectId'])) ?>" data-file="<?= isset($family['familyPhoto']['name']) ? $family['familyPhoto']['name'] : '' ?>"></td>
											-->
											<td class="no-comma"><a href="<?= $this->links('family_details', array('family_id' => $family['objectId'])) ?>"><?= isset($family['lastName']) ? $family['lastName'] : '' ?></a></td>
											<td><a href="<?= $this->links('family_details', array('family_id' => $family['objectId'])) ?>"><?= isset($family['firstName']) ? $family['firstName'] : '' ?></a></td>
											<td><?= isset($family['addressLine1']) ? $family['addressLine1'] : '' ?></td>
											<td><?= isset($family['phone']) ? $family['phone'] : '' ?></td>
											<td class="no-comma"><a class="no_follow" href="mailto:<?= isset($family['email']) ? $family['email'] : '' ?>"><?= isset($family['email']) ? $family['email'] : '' ?></a></td>
											<td><button data-href="<?= $this->links('family_delete', array('family_id' => $family['objectId'])) ?>" data-file="<?= isset($family['familyPhoto']['name']) ? $family['familyPhoto']['name'] : '' ?>" class="button button-red delete_duplicate">Delete</button></td>
										</tr>
										<? if (count($families)-1 > $key): ?>
											<tr>
												<td colspan="6">
													<div class="row-fluid">
														<button class="button button-green merge_bottom_top span5"><i class="fa fa-arrow-up right-margin-10"></i>Merge bottom into top</button>
														<button class="button button-green merge_top_bottom span5"><i class="fa fa-arrow-down right-margin-10"></i>Merge top into bottom</button>
														<div class="span2 text-center">
															<i id="merge-tooltip" data-toggle="tooltip" title="" data-original-title="Merge bottom into top: If both records have a field, the bottom one is deleted and the top is kept. Merge top into bottom: If both records have a field, the top one is deleted and the bottom is kept." class="dripicon-question tool-tip"></i>
														</span>
													</div>
												</td>
											</tr>
										<? endif; ?>
									<? endforeach; ?>
								</tbody>
							</table>
							  <section>
								
							  </section>
						</div>
					<? endforeach; ?>
			  	<? else: ?>
					<p>
						No duplicate families found.
					</p>
				<? endif; ?>
			</div>
			<? if (count($this->duplicateFamilies) > 0): ?>
				<section>
					<div style="float: left;" class="pagination">
						<ul>
							<li><a data-slide="prev" href="#myCarousel" class="left no_follow">‹</a></li>
							<li><a data-slide="next" href="#myCarousel" class="right no_follow">›</a></li>
						</ul>
					</div>
				</section>
			<? endif; ?>
		</div>
    </div>
	<!--tab-container #duplicates-->
    <div class="tab-container" id="new-families" style="display: none;">
		<table class="table table-striped table-hover new_families_table">
			<thead class="table-headers">
				<tr>
					<th width="1%">
						<input type="checkbox" class="approve_all">
					</th>
					<th width="20%">
						<a class="desc" data-db-attr="lastName" href="#"></a>
						<a class="asc" data-db-attr="lastName" href="#"></a>
						Last Name
					</th>
					<th width="20%">
						<a class="desc2" data-db-attr="firstName" href="#"></a>
						<a class="asc2" data-db-attr="firstName" href="#"></a>
						First Name
					</th>
					<th width="25%">Address</th>
					<th width="15%">Phone</th>
					<th width="18%">Email</th>
				</tr>
			</thead>  
			<tbody>

			</tbody>
		</table>
		<section class="directory-edit-footer">
			<div class="row-fluid">
				<div class="span9">
					<p>Select families to be added to your directory.</p>
				</div>
			</div>
		</section>
		<!--directory-edit-footer-->
    </div>
	<!--tab-container #new-families-->
</div>
<!--app-body-content-->
<div aria-hidden="false" aria-labelledby="deleteModal" role="dialog" tabindex="-1" class="modal delete-parish-modal hide fade in" id="deleteParishModal">
	<div class="modal-header">
		<button aria-hidden="true" data-dismiss="modal" class="close clearClose" type="button">×</button>
		<h3 class="text-centered " id="deleteModal">Delete Parish Directory</h3>
	</div>
	<!--modal-header-->
	<div class="modal-body text-centered">
		<h4 class="large-header bottom-margin-30">Remove <?= $this->familiesCount ?> Families?</h4>
		<p>We hate to be a pain, but we want to make sure you realize what you are about to do. You are going to delete your entire directory. If you wish to proceed, go ahead and type <b>"DELETE"</b> in the text field below.</p>
		<form class="top-margin-10 delete-directory-form">
			<div class="form-group span8">
				<input type="text" required="" autofocus="true" placeholder="DELETE" id="delete-directory">
				<input type="submit" class="button button-red DeleteAllFamilies" value="Delete">
			</div>
		</form>

		<div class="progress progress-danger progress-striped active hide">
  			<div class="progress bar"  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
    			<span class="sr-only">0%</span>
  			</div>
		</div>

	</div>
	<!--modal-body-->
	<div class="modal-footer">
		<small>Contact us if you need help <a href="mailto:support@oneparish.com">support@oneparish.com</a></small>
	</div>
	<!--modal-footer-->
</div>
<!--#deleteParishModal-->

<div aria-hidden="false" aria-labelledby="deleteModal" role="dialog" tabindex="-1" class="modal delete-parish-modal hide fade in" id="mergefamilyModal">
	<div class="modal-header">
		<button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
		<h3 class="text-centered " id="deleteModal">Delete Parish Directory</h3>
	</div>
	<!--modal-header-->
	<div class="modal-body text-centered">
		<h4 class="large-header bottom-margin-30">Merge families</h4>
		<p>Which record is the 'master' record that will retain the information?</p>
		<form class="top-margin-10 merge-families-form">
			<div class="form-group span8">
				<table class="table table-striped table-hover directory_table merge-families-table"><thead class="table-headers"><tr><th width="1%"></th><th width="20%">Last Name</th><th width="20%">First Name</th><th width="25%">Address</th><th width="15%">Phone</th><th width="18%">Email</th></tr></thead><tbody><tr>
				</tr></tbody></table>

				<input type="submit" class="button button-red" value="Delete">
			</div>
		</form>
	</div>
	<!--modal-body-->
	<div class="modal-footer">
		<small>Contact us if you need help <a href="mailto:support@oneparish.com">support@oneparish.com</a></small>
	</div>
	<!--modal-footer-->
</div>
<!--#mergefamilyModal-->
<script type="text/javascript">
	var mergeUrl = "<?= $this->links('merge_families') ?>",
		deleteDirectoryURL = "<?= $this->links('delete_directory') ?>",
		families = <?= json_encode($this->jsonDuplicates) ?>,
		allFamiliesCount = <?= $this->familiesCount ?>;
</script>