<section class="app-page-header">
  <div class="row-fluid">
    <div class="span9">
      <h2>Family Details</h2>
    </div>
  </div>
</section>
<div class="app-body-content family-details-content">
	<form class="edit-family validate-me agile" action="" method="post">
	    <section>
	  		<div class="row-fluid">
		        <div class="span7">
		          <h4 class="subhead"> <a class="no_follow" href="javascript:history.back()"><i class="fa fa-arrow-left"></i></a> <?= isset($this->family['lastName']) ? $this->family['lastName'] : '' ?>'s Information</h4>
		        </div>
		        <div class="span5">
			        <p class="family-code text-caps pull-right">
			           <i class="dripicon-question tool-tip" data-original-title="The family access code is used to let family members join an existing family." title="" data-toggle="tooltip" id="help-tooltip"></i> Family Access Code: 
			           <input type="text" class="small-input" placeholder="123456" name="accessCode" value="<?= isset($this->family['accessCode']) ? $this->family['accessCode'] : '' ?>">
			        </p>
		        </div>
	  		</div>
	  	</section>
	    <section class="detail-section family-details">
		    <div class="row-fluid">      
		        <div class="span4">
		         	<div class="family-img">
		            	<img src="<?= isset($this->family['familyPhoto']['url']) ? $this->family['familyPhoto']['url'] : 'http://placehold.it/350x350' ?>">            
		          	</div>
		          	<input type="file" name="familyPhoto" id="family_photo">
		          	<label class="horizontal-form-label top-margin-10">
		            	<input type="checkbox" value="true" <?= isset($this->family['approved']) && $this->family['approved'] ? 'checked="checked"' : '' ?> class="public-profile" name="approved">
		            	Approve Family
		          	</label>
		        </div>
		        <div class="span7 offset1">
		        	<div class="row">
						<div class="span6">
							<label>First Name</label>
							<input type="text" class="half-input" data-validation="FirstNameValid" value="<?= isset($this->family['firstName']) ? $this->family['firstName'] : '' ?>" placeholder="First Name" name="firstName">
						</div>
						<div class="span6">
							<label>Last Name</label>
							<input type="text" class="half-input" data-validation="LastNameValid" value="<?= isset($this->family['lastName']) ? $this->family['lastName'] : '' ?>" placeholder="Last Name" name="lastName">
						</div>
					</div>
					<div class="row">
						<div class="span12">
							<label>Street Address</label>
							<input type="text" class="full-input" value="<?= isset($this->family['addressLine1']) ? $this->family['addressLine1'] : '' ?>" placeholder="Street Address" name="addressLine1">
						</div>
					</div>
					<div class="row">
						<div class="span5">
							<label>City</label>
							<input type="text" class="half-input" value="<?= isset($this->family['addressCity']) ? $this->family['addressCity'] : '' ?>" placeholder="City" name="addressCity">
						</div>
						<div class="span2">
							<label>State</label>
							<input type="text" class="small-input" data-validation="length" data-validation-length="max2" value="<?= isset($this->family['addressState']) ? $this->family['addressState'] : '' ?>" placeholder="State" name="addressState">
						</div>
						<div class="span5">
							<label>Zip Code</label>
							<input type="text" class="half-input" value="<?= isset($this->family['addressZip']) ? $this->family['addressZip'] : '' ?>" placeholder="Zipcode" name="addressZip">
						</div>
					</div>
					<div class="row">
						<div class="span5">
							<label>Email Address</label>
							<input type="email" class="half-input" data-validation="email" data-validation-optional="true" value="<?= isset($this->family['email']) ? $this->family['email'] : '' ?>" placeholder="Email Address" name="email">
						</div>
						<div class="span4">
							<label>Phone Number</label>
							<input type="text" class="half-input" data-validation="PhoneNumberValid" data-validation-optional="true" value="<?= isset($this->family['phone']) ? $this->family['phone'] : '' ?>" placeholder=" Home phone number" name="phone">
						</div>
						<div class="span3">
							<label>Envelope #</label>
							<input type="text" class="half-input" value="<?= isset($this->family['envelopeNumber']) ? $this->family['envelopeNumber'] : '' ?>" placeholder="1001" name="envelopeNumber">
						</div>
					</div>
					<div class="form-group span12">
						<div class="pull-right">
							<input type="submit" name="saveFamily" class="button button-green pull-right" value="Save" />
							<div class="loader-here pull-right right-margin-15"></div>
							<input type="submit" name="deleteFamily" data-href="<?= $this->links('family_delete', array('family_id' => $this->family['objectId'])) ?>" data-file="<?= isset($this->family['familyPhoto']['name']) ? $this->family['familyPhoto']['name'] : '' ?>" class="button button-red pull-right right-margin-15 deletefamily" value="Delete" />
						</div>
					</div>
		        </div>
		   	</div>
	    </section>
 	</form>
 	<section class="detail-section no-border-bottom">
   		<div class="row-fluid">
      		<div class="span9">
         		<h4 class="subhead">Members</h4>
      		</div>
      		<div class="pull-right">
        		<h4><a class="new-member" href="#">+ Add new</a></h4>
    		</div>
		    <div class="add-new-member">
		        <form class="edit-member form-horizontal validate-me agile" method="post" action="<?= $this->links('add_person') ?>">
		  			<br>
				  	<div class="form-group span10">
				  		<div class="span3">
				  			<label class="horizontal-form-label">First Name</label>
				  		</div>
				  		<div class="span9">
					  		<input type="text" required="" value="" data-validation="FirstNameValid" placeholder="John" class="horizontal-input" name="firstName">
				  		</div>
				  	</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Last Name</label>
		  				</div>
			  			<div class="span9">
		  					<input type="text" value="" placeholder="Baker" data-validation="LastNameValid" class="horizontal-input" name="lastName">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Birthday</label>
		  				</div>
		  				<div class="span9">
		  					<input type="date" value="" data-validation="date" data-validation-format="dd/mm/yyyy" data-validation-optional="true" placeholder="mm/dd/yyyy" class="horizontal-input birthday" name="birthday">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Email</label>
		  				</div>
		  				<div class="span9">
		  					<input type="email" value="" placeholder="john@oneparish.com" data-validation="email" data-validation-optional="true" class="horizontal-input" name="email">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Phone</label>
		  				</div>
		  				<div class="span9">
		  					<input type="text" data-validation="PhoneNumberValid" data-validation-optional="true" value="" placeholder="(123) 456-7891" class="horizontal-input" name="phone">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Facebook</label>
		  				</div>
						<div class="span9">
		  					<input type="text" value="" placeholder="facebook.com/joe.catholic" class="horizontal-input" name="facebook">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label class="horizontal-form-label">Twitter</label>
		  				</div>
		  				<div class="span9">
		  					<input type="text" value="" placeholder="@joecatholic" class="horizontal-input" name="twitter">
		  				</div>
		  			</div>
		  			<div class="form-group span10">
		  				<div class="span3">
		  					<label>Picture</label>
		  				</div>
		  				<div class="span9">
		  					<input type="file" name="picture" class="member_picture">
				  			<input type="hidden" name="family_id" value="<?= isset($this->family['objectId']) ? $this->family['objectId'] : '' ?>">
				  			<input type="hidden" name="parish" value="<?= isset($this->family['parish']['objectId']) ? $this->family['parish']['objectId'] : '' ?>">
							<button type="submit" name="addNewMember" class="button button-green pull-right" value="save">Save</button>
							<button type="button" class="button button-red pull-right right-margin-15 cancel-member">Cancel</button>
		  				</div>
		  			</div>
				</form>
		    </div>
		    <!--add-new-member-->
    	</div>
	    <div class="row-fluid">
	    	<div class="span12">
	        	<dl class="family-member-container">
	        		<? foreach ($this->persons as $key => $person): ?>
		        		<dd data-member-id="<?= $person->objectId ?>" class="row-fluid family-member">
							<div class="span9">
								<ul>
									<li><img class="family-member-avatar" src="<?= isset($person->picture->url) ? $person->picture->url : 'http://f.cl.ly/items/2H211Q3s3W0k0q1R3i0m/default-avatar.png' ?>"></li><!--default avatar-->
									<li class="member-name"><?= $person->firstName .' '. $person->lastName ?></li>
								</ul>
							</div>
							<div class="span3 text-right edit-trigger">
								<a href="#"></a>
							</div>
							<!--edit-trigger-->
							<div class="span12 edit-member-form">
								<form class="edit-member form-horizontal validate-me agile" method="post" action="<?= $this->links('edit_person', array('person_id' => $person->objectId)) ?>">
								 	<br>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">First Name</label>
								  		</div>
								  		<div class="span9">
								  			<input type="text" required="" data-validation="FirstNameValid" value="<?= isset($person->firstName) ? $person->firstName : '' ?>" placeholder="John" class="horizontal-input" name="firstName">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Last Name</label>
								  		</div>
								  		<div class="span9">
									  		<input type="text" data-validation="LastNameValid" value="<?= isset($person->lastName) ? $person->lastName : '' ?>" placeholder="Baker" class="horizontal-input" name="lastName">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Birthday</label>
								  		</div>
								  		<div class="span9">
									  		<input type="date" data-validation="date" data-validation-format="dd/mm/yyyy" data-validation-optional="true" value="<?= isset($person->birthday->iso) ? date('m/d/Y', strtotime($person->birthday->iso)) : '' ?>" placeholder="mm/dd/yyyy" class="horizontal-input birthday" name="birthday">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Email</label>
								  		</div>
								  		<div class="span9">
									  		<input type="email" data-validation="email" data-validation-optional="true" value="<?= isset($person->email) ? $person->email : '' ?>" placeholder="john@oneparish.com" class="horizontal-input" name="email">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Phone</label>
								  		</div>
								  		<div class="span9">
									  		<input type="text" data-validation="PhoneNumberValid" data-validation-optional="true" value="<?= isset($person->phone) ? $person->phone : '' ?>" placeholder="(123) 456-7891" class="horizontal-input" name="phone">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
								  		<div class="span3">
								  			<label class="horizontal-form-label">Facebook</label>
								  		</div>
								  		<div class="span9">
								  			<input type="text" value="<?= isset($person->facebook) ? $person->facebook : '' ?>" placeholder="facebook.com/joe.catholic" class="horizontal-input" name="facebook">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
									  	<div class="span3">
								  			<label class="horizontal-form-label">Twitter</label>
								  		</div>
								  		<div class="span9">
								  			<input type="text" value="<?= isset($person->twitter) ? $person->twitter : '' ?>" placeholder="@joecatholic" class="horizontal-input" name="twitter">
								  		</div>
								  	</div>
								  	<div class="form-group span10">
									  	<div class="span3">
									  		<label>Picture</label>
								  		</div>
								  		<div class="span9">
								  			<input type="file" name="picture" class="member_picture">
								  			<input type="hidden" name="family_id" value="<?= isset($this->family['objectId']) ? $this->family['objectId'] : '' ?>">
								      		<button type="submit" name="saveMember" class="button button-green pull-right" value="save">Save</button>
								      		<div class="loader-here pull-right right-margin-15"></div>
								      		<a class="member_destory button button-red pull-right right-margin-10" data-user-id="<?= isset($person->user->objectId) ? $person->user->objectId : '' ?>" data-id="<?= isset($person->objectId) ? $person->objectId : '' ?>" data-file="<?= isset($person->picture->name) ? $person->picture->name : '' ?>" href="#">Remove</a>
								  		</div>
								  	</div>
								</form>
							</div>
							<!--edit-member-form-->
						</dd>
					<? endforeach; ?>
	        	</dl>
	     	</div>
	    </div>
  	</section>
</div>
<!--app-body-content-->
<div class="alert alert-danger" style="display: none;">Oops. We were not able to save your information. Please try again.</div>
<script>
  	var deleteUrl = "<?= $this->links('delete_person', array('person_id' => 'replacement')) ?>";
	if (typeof familyDetails == "undefined")
		$.getScript("<?= My_Core::getApplicationUri() . $this->getJs('familydetails.js', 'families') ?>");

	$.formUtils.addValidator({
		name : 'FirstNameValid',
		validatorFunction : function(value, $el, config, language, $form) {
			//var usernameRegex = '/^([a-zA-Z&]+)$/';
			return value.match(/^([a-zA-Z&\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only characters and &',
		errorMessageKey: 'badEvenNumber'
	}); 

	$.formUtils.addValidator({
		name : 'LastNameValid',
		validatorFunction : function(value, $el, config, language, $form) {
			return value.match(/^([a-zA-Z-\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only characters and -',
		errorMessageKey: 'badEvenNumber'
	});

	$.formUtils.addValidator({
		name : 'PhoneNumberValid',
		validatorFunction : function(value, $el, config, language, $form) {
			return value.match(/^([0-9-()\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only numbers and - or ( )',
		errorMessageKey: 'badEvenNumber'
	}); 

	$.validate({
	  form : '.validate-me'
	});

</script>