<script src="<?= $this->getJs('uploaddirectory.js', 'families') ?>"></script>
<script src="<?= $this->getJs('select.js', 'families') ?>"></script>
<? $this->headLink()->appendStylesheet($this->getStyle('select.css', 'families'), 'screen') ?>

<section class="app-page-header">
	<h2>Import Batch / Update</h2>
</section>
<div class="app-body-content">
  <section class="directory_upload">
      <!--start-progress-bar-->
              <div id="rootwizard">
                <div class="progress-nav">
                  <div class="progress-inner">
                    <ul class="cf btn-striped active-trp">
                          <li class="arrow_box active"><span>Choose Type</span></li>
                          <li class="arrow_box"><span>Choose File</span></li>
                          <li class="arrow_box"><span>Set Fields</span></li>
                          <li class="arrow_box"><span>Confirm</span></li>
                      </ul>
                    </div>
                </div>

                <div class="tab-content upload-csv-tabs">
                  <div class="tab-pane cf active" id="tab1">
                      <div class="row-fluid top-margin-50">
                        
                        <div class="span4 text-center">
                          <h1 class="no-border-bottom"><button class="button button-green">Only Add New Families</button></h1>
                          <p>You only want to add new families <br/>( or upload your directory for the first time )</p>
                          <p>Any families in your file that currently exist in the directory will be ignored.</p>
                        </div>
                        <div class="span4 text-center">
                          <h1 class="no-border-bottom"><button class="button button-green">Add & Update Families</button></h1>
                          <p>New families will be imported and any current families will be updated.</p>
                          <p>You can choose to overwrite the directory for all fields in the import file or only add fields from the import file that are currently blank in the directory.</p>
                        </div>
                        <div class="span4 text-center">
                          <h1 class="no-border-bottom"><button class="button button-green">Only update existing Families</button></h1>
                          <p>Only update records that currently exist.</p>
                          <p>You can choose to overwrite the directory for all fields in the import file or only add fields from the import file that are currently blank in the directory.</p>
                        </div>
                      </div>
                  </div>
                  <!--#tab-1-->
                  <div class="tab-pane cf" id="tab2">
                      <section class="directory-upload-container directory_upload dropzone">
                        <div class="row-fluid">
                          <div class="span12">
                            <h1 class="upload-icon"><i class="dripicon-document clickable"></i></h1>
                            <h1 class="clickable">Click or drop here the .CSV file to upload.</h1>           
                            <div id="previews" class="dropzone-previews"></div>
                            <h5 class="directory-upload-message alert-danger">
                              We cannot upload this directory as you do not have enough columns to match ours.<br><br>
                              No worries! Email your directory to <a href="mailto:oneparish@gmail.com">oneparish@gmail.com</a>. We'll take care of it for you.
                            </h5>
                          </div>
                        </div>
                      </section>
                      <!--directory-upload-container-->
                  </div>
                  <!--#tab2-->
                  	<div class="tab-pane cf" id="tab3">
						<div class="row-fluid">
							<div class="span3">
								<h3 class="text-centered">Your Directory</h3>
								<p class="text-centered"><small>Drag your table headers from here</small></p>
								<div class="widget-body">
									<!--<ul id="sortable" class="ui-sortable ui-draggable">-->
									<ul id="sortable1" class="droptrue">
										<li data-id="item-1" class="widget-draggable">Sort 1</li>
										<li data-id="item-2" class="widget-draggable">Sort 2</li>
										<li data-id="item-3" class="widget-draggable">Sort 3</li>
										<li data-id="item-4" class="widget-draggable">Sort 4</li>
										<li data-id="item-5" class="widget-draggable">Sort 5</li>
										<li data-id="item-6" class="widget-draggable">Sort 6</li>			
										<li data-id="item-7" class="widget-draggable">Sort 7</li>			
										<li data-id="item-8" class="widget-draggable">Sort 8</li>
									</ul>
								</div>
								<!--widget-body-->
							</div>
							<div class="span9">
								<div class="row-fluid">
									<div class="span4">
										<h3 class="text-centered">File Field</h3>
										<p class="text-centered"><small class="text-centered">Drag here</small></p>
										<div class="widget-body">
							            	<ul id="sortable2" class="droptrue dropfalse">
							             	</ul>
						            	</div>
						            </div>
						            <!--span4-->
						            <div class="span4">
										<h3 class="text-centered"><i class="fa fa-long-arrow-right"></i></h3>
										<p class="text-centered"><small class="text-centered">Choose action</small></p>
										<div class="widget-body action-fields">
										<ul class="sort-container"></ul>
										</div>
						            </div>
						            <!--span4-->
						            <div class="span4">
						            	<h3 class="text-centered">Directory Field</h3>
						            	<p class="text-centered"><small class="text-centered">Fields matching in our Directory</small></p>
										<div class="widget-body">
							            	<ul>
							            		<li class="widget-draggable">Family Last Name</li>
							            		<li class="widget-draggable">Family Name Format (John &amp; Mary)</li>
							                	<li class="widget-draggable">Family Address 1</li>
							                	<li class="widget-draggable">Family Address 2</li>
							                	<li class="widget-draggable">Family City</li>
							                	<li class="widget-draggable">Family Zip</li>
							                	<li class="widget-draggable">Family Primary Phone</li>
							                	<li class="widget-draggable">E Mail E-Mail Address</li>
							             	</ul>
						            	</div>
						            </div>
						            <!--span4-->
					            </div>
					            <!--row-fluid-->
							</div>
							<!--span9-->
						</div>
						<!--row-fluid-->
                  	</div>
                  	<!--#tab-3-->
                	<div class="tab-pane cf" id="tab4">
                		<div class="row-fluid">
                			<div class="span4">
                				<h3>Type: .CSV</h3>
                				<h3>File Name: File Name Here</h3>
                			</div>
                			<!--span4-->
                		</div>
                		<!--row-fluid-->
                		<div class="row-fluid">
                			<div class="span12">
                				<h3>Example:</h3>
                			</div>
                			<!--span12-->
                		</div>
                		<div class="row-fluid">
                			<div class="span4">
                				<div class="widget-body">
                					<ul class="results-here">
										<li data-id="item-1" class="widget-draggable">Andrzejewski</li>
										<li data-id="item-2" class="widget-draggable">Adam & Kerrya</li>
										<li data-id="item-3" class="widget-draggable">225 N. Washington St.</li>
										<li data-id="item-4" class="widget-draggable">&nbsp;</li>
										<li data-id="item-5" class="widget-draggable">Washington</li>
										<li data-id="item-6" class="widget-draggable">31337</li>			
										<li data-id="item-7" class="widget-draggable">(630) 974-6140</li>			
										<li data-id="item-8" class="widget-draggable">test@test.com</li>
									</ul>
                				</div>
                			</div>
                			<div class="span4">
                				<div class="widget-body">
                					<ul>
                						<li class="widget-draggable option-action" data-id="">
                							Always Replaces
                						</li>
                					</ul>
                				</div>
                			</div>
                			<div class="span4">
                				<div class="widget-body">
					            	<ul>
					            		<li class="widget-draggable">Family Last Name</li>
					            		<li class="widget-draggable">Family Name Format (John &amp; Mary)</li>
					                	<li class="widget-draggable">Family Address 1</li>
					                	<li class="widget-draggable">Family Address 2</li>
					                	<li class="widget-draggable">Family City</li>
					                	<li class="widget-draggable">Family Zip</li>
					                	<li class="widget-draggable">Family Primary Phone</li>
					                	<li class="widget-draggable">E Mail E-Mail Address</li>
					             	</ul>
				            	</div>
                			</div>
                		</div>
                		<!--row-fluid-->

                  	</div>
                  	<!--#tab4-->
                  	<ul class="pager slider-pager hide">
                    	<li class="previous"><a href="#">Previous</a></li>
                    	<li class="next"><a href="#">Next</a></li>
                  	</ul>
                </div>  
                <!--tab-content-->
                <ul class="button-pager top-margin-30 hide">
                    <li class="button button-green pull-left previous"><a href="#">Previous</a></li>
                    <li class="button button-green pull-right next disabled"><a href="#">Next</a></li>
                </ul>
               </div>
               <!--#rootwizard-->
        <!--end-progress-bar-->
  </section>
</div>
<!--app-body-content-->