<section class="app-page-header">
  <div class="row-fluid">
    <div class="span8">
  	 <h2>Parish Directory | Families: <span class="green-text"><?= $this->familiesCount ?></span></h2>
    </div>
    <dl class="family-search">
      <dd>
      	<form class="family-search-form agile" action="">
        	<input name="search" type="text" class="search-input search-family" value="<?= isset($this->search) ? $this->search : '' ?>" placeholder="Search By Last Name" id="directory_search">
			<div id="floatingCirclesG" class="hide">
				<div class="f_circleG" id="frotateG_01"></div>
				<div class="f_circleG" id="frotateG_02"></div>
				<div class="f_circleG" id="frotateG_03"></div>
				<div class="f_circleG" id="frotateG_04"></div>
				<div class="f_circleG" id="frotateG_05"></div>
				<div class="f_circleG" id="frotateG_06"></div>
				<div class="f_circleG" id="frotateG_07"></div>
				<div class="f_circleG" id="frotateG_08"></div>
			</div>
			<!--circular loading-->
        	<a class="search-trigger" href="#"><i class="dripicon-search"></i></a>
        </form>
      </dd>
      <dd><a class="add-new-family" href="<?= $this->links("add_family") ?>" title="Add New Family"><i class="dripicon-user-group"></i></a></dd>
      <dd><a class="export-directory" href="#" onclick="alert('Coming soon!');return false;"><i class="dripicon-download"></i></a></dd>
      <div id="suggestions-container" class="hide"></div>
      <!--suggestions-container-->
    </dl>
  </div>
</section>
<section class="app-body-content">
  <div class="row-fluid">
    <div class="span12">    
		<div id="searchResults" class="hide">
			<br>
			<p class="top-margin-30"></p>
		</div>
  		<table id="data-table" class="table table-striped table-hover directory_table families-table" url="<?= $this->links('parish_directory') ?>">
		<thead class="table-headers">
			<tr>
				<th width="20%">
					  <a title="Desc" class="order desc" data-db-attr="lastName" href="?orderBy=lastName&orderType=Desc<?= isset($this->search) ? '&search='.$this->search : '' ?>"></a>
					  <a title="Asc" class="order asc" data-db-attr="lastName" href="?orderBy=lastName&orderType=Asc<?= isset($this->search) ? '&search='.$this->search : '' ?>"></a>
					  Last Name
				</th>
				<th width="20%">
					  <a title="Desc" class="order desc" data-db-attr="firstName" href="?orderBy=firstName&orderType=Desc<?= isset($this->search) ? '&search='.$this->search : '' ?>"></a>
					  <a title="Asc" class="order asc" data-db-attr="firstName" href="?orderBy=firstName&orderType=Asc<?= isset($this->search) ? '&search='.$this->search : '' ?>"></a>
					  First Name
				</th>
				<th width="25%">Address</th>
				<th width="15%">Phone</th>
				<th width="18%">Email</th>
				<th width="2%"></th>
			</tr>
		</thead>  
		<tbody>
		  	<? if ($this->familiesCount > 0): ?>
			  	<? foreach ($this->families as $key => $family): ?>
			      	<tr url="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>">
						<td><a href="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>"><?= isset($family->lastName) ? $family->lastName : '' ?></a></td>
						<td><a href="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>"><?= isset($family->firstName) ? $family->firstName : '' ?></a></td>
						<td><?= (isset($family->addressLine1) ? $family->addressLine1 : '') . (isset($family->addressLine2) ? $family->addressLine2 : '') . (isset($family->addressZip) ? ', '.$family->addressZip : '') ?></td>
						<td><?= isset($family->phone) ? $family->phone : '' ?></td>
						<td><?= isset($family->email) ? '<a class="no_follow" href="mailto:'. $family->email .'">'. $family->email .'</a>' : '' ?></td>
						<td><a href="<?= $this->links('family_details', array('family_id' => $family->objectId)) ?>" class="dripicon-document-edit grey-link edit-user"></a></td>
						<td><a href="#" data-href="<?= $this->links('family_delete', array('family_id' => $family->objectId)) ?>" class="fa fa-times reject user_destroy no_follow deleteFamily" data-file="<?= isset($family->familyPhoto->name) ? $family->familyPhoto->name : '' ?>" data-id="<?= isset($family->objectId) ? $family->objectId : '' ?>"></a></td>
			      	</tr>
			  	<? endforeach; ?>
		  	<? else: ?>
				<tr>
					<td colspan="6">We did not find and families matching your criteria.</td>
				</tr>
		  	<? endif; ?>
		</tbody>
  		</table>
    	<div class="pagination light-theme simple-pagination">
	      	<ul>
			  	<? if ($this->familiesCount > 0): ?>
					<?= $this->pagination->display() ?>
				<? endif; ?>
	      	</ul>
      	</div>
    </div>
  </div>
</section>
<script>
	ajaxData = <?= json_encode($this->families) ?>;
	$.getScript("<?= My_Core::getApplicationUri() . $this->getJs('viewallfamilies.js', 'families') ?>");
</script>