	<!-- Modal placeholder -->
	<div id="waitModal">
		<div class="loader-container hide">
			<div class="loader"> <div class="loading-bar"></div>
			<div class="loading-bar"></div> <div class="loading-bar"></div> </div>
			<h4 class="text-caps">Please wait, our system is processing your request...</h4>
		</div>
	</div>
	<!-- EO Modal placeholder -->
	<!-- Interventions -->
	<? if (count($this->bridge()->getInterventions())) { ?> 
		<script type="text/javascript">
			<? foreach ($this->bridge()->getInterventions() as $intervention) { ?>
				VanillaZF.interventions.push({timestamp: "<?= $intervention['timestamp'] ?>", message: "<?= $this->escape($intervention['message']) ?>", priority: "<?= $intervention['priority'] ?>", priorityName: "<?= $intervention['priorityName'] ?>"});
			<? } ?>
		</script>
	<? } ?>
	<div id="interventions"></div>
	<!-- EO Interventions -->
</body>

</html>