<?= $this->doctype("XHTML1_STRICT") ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<? 
	$this->headLink(array('rel' => 'icon', 'href' => $this->getImage('favicon.png'), 'type' => 'image/x-icon'), 'PREPEND');
	$this->headLink(array('rel' => 'shortcut icon', 'href' => $this->getImage('favicon.png'), 'type' => 'image/x-icon'), 'PREPEND');

	$this->headLink()->prependStylesheet($this->getStyle('style-ie8.css'), 'screen', 'IE 8');
	$this->headLink()->prependStylesheet($this->getStyle('style-ie7.css'), 'screen', 'IE 7');
	$this->headLink()->prependStylesheet($this->getStyle('style-ie6.css'), 'screen', 'IE 6');
	$this->headLink()->prependStylesheet($this->getStyle('font-awesome.min.css'), 'screen');
	$this->headLink()->prependStylesheet($this->getStyle('dripicons.css'), 'screen');
	$this->headLink()->prependStylesheet($this->getStyle('fullcalendar.print.css'), 'screen');
	$this->headLink()->prependStylesheet($this->getStyle('fullcalendar.css'), 'screen');
	$this->headLink()->prependStylesheet($this->getStyle('style.css'), 'screen');

	$this->headScript()->prependFile($this->getJs('jquery.form-validator.min.js'));
	$this->headScript()->prependFile($this->getJs('jquery.autocomplete.js'));
	$this->headScript()->prependFile($this->getJs('jquery.fileupload.js'));
	$this->headScript()->prependFile($this->getJs('fullcalendar.min.js'));
	$this->headScript()->prependFile($this->getJs('jquery.tablesorter.js'));
	$this->headScript()->prependFile($this->getJs('sidebar.js'));
	$this->headScript()->prependFile($this->getJs('vanillazf.js'));
	$this->headScript()->prependFile($this->getJs('bootstrap.js'));
	$this->headScript()->prependFile($this->getJs('dropzone.min.js'));
	$this->headScript()->prependFile($this->getJs('jquery.form.js'));
	$this->headScript()->prependFile($this->getJs('jquery.ui.js'));
	$this->headScript()->prependFile($this->getJs('jquery.js'));
	$this->headScript()->prependFile($this->getJs('moment.min.js'));

	$this->headTitle(My_Core::getConfig()->application->name);

	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
	$this->headMeta()->appendHttpEquiv('Content-Language', 'en-US');
?>

<?= $this->headMeta() ?>

<?= $this->headLink() ?>

<?= $this->headStyle() ?>

<?= $this->headScript() ?>

<?= $this->headTitle() ?>

</head>
<body class="<?= $this->layout()->getLayout() ?>">
