<?= $this->partial('_header.phtml', $this->getVars()) ?>

<div class="mainHeader">
	<nav role="navigation" class="navbar navbar-fixed-top">
		<div class="logo-container">
			<a class="logo-link no_follow" href="/"><div class="logo-admin">One Parish</div></a>
		</div>
		<div id="navbar-container" class="navbar-container">
			<div role="navigation" class="navbar-header pull-right">
				<ul class="nav ace-nav">
					<li>
						<a class="hover-me" href="" data-toggle="dropdown">
							<span class="user-info"><?= $this->user->firstName .' '. $this->user->lastName ?></span><i class="fa fa-angle-down"></i>
						</a>				
						<ul class="user-menu pull-right dropdown-menu">
							<li>
								<a class="password-reset" href="#">Reset Password</a>
							</li> 
							<li class="divider"></li>
							<li>
								<a href="<?= $this->links('logout') ?>"><i class="dripicon-cross"></i>Logout</a>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<!--header nav -->
</div>
<!-- /.mainHeader -->

<div class="wrapper cf">
	
	<?= $this->partial('_sidebar.phtml', $this->getVars()) ?><?php //get the sidebar ?>
	<?= $this->partial('_sidebar_modal.phtml', $this->getVars()) ?><?php //get the contact us modal ?>
	
	<div class="content">
		<div class="view">
			<?= $this->layout()->content ?>
		</div>
		<!-- alert message when deleting families-->
		<div class="alert alert-success" style="display: none;">We successfully removed these families.</div>
	</div>
	

	
</div>
<!--wrapper-->

<footer>
	<!--<p class="help-block"><?= $this->translate('This is the footer') ?></p>-->
</footer>

<?= $this->partial('_footer.phtml', $this->getVars()) ?>