<section class="app-page-header">
	<h2><?= isset($this->group) ? 'Edit "'.$this->group['name'].'" Parish Group' : 'Create New Parish Group' ?></h2>
</section>
<div class="app-body-content new-group-wrapper">

	<section class="detail-section">
		<div class="row-fluid">
			<div class="span12">
				<h4 class="subhead">Group Information</h4>
				<p><?= isset($this->group) ? 'Update your group\'s information.' : 'Please fill out the form below to add the group to your parish.' ?></p><br>
			</div>
			<form class="form-horizontal validate-me agile" method="post" action="">
				
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Group Name</label>
					</div>
					<div class="span9">
						<input type="text" data-validation="OnlyChar" value="<?= isset($this->group['name']) ? $this->group['name'] : '' ?>" placeholder="Enter The Group Name" class="horizontal-input" name="name">
					</div>
				</div>

				
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Phone No.</label>
					</div>
					<div class="span9">
						<input type="text" data-validation="PhoneNumberValid" data-validation-optional="true" value="<?= isset($this->group['phone']) ? $this->group['phone'] : '' ?>" placeholder="(123) 456-7891" class="horizontal-input" name="phone">
					</div>
				</div>

				
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Email</label>
					</div>
					<div class="span9">
						<input type="text" data-validation="email" data-validation-optional="true" value="<?= isset($this->group['email']) ? $this->group['email'] : '' ?>" placeholder="example@oneparish.com" class="horizontal-input" name="email">
					</div>
				</div>

				
				<div class="form-group span10">
					<div class="span3">
						<label class="horizontal-form-label">Website</label>
					</div>
					<div class="span9">
						<input type="text" value="<?= isset($this->group['website']) ? $this->group['website'] : '' ?>" placeholder="www.oneparish.com" class="horizontal-input" name="website">
					</div>
				</div>

				
				<div class="form-group span12">
					<div class="span4 pull-right">
						<button class="button button-green pull-right">Save</button>
					</div>
				</div>
			</form>
		</div>
	</section>

</div>

<div class="alert alert-success" style="display: none;">We successfully saved this group.</div>
<script>
	$.formUtils.addValidator({
		name : 'OnlyChar',
		validatorFunction : function(value, $el, config, language, $form) {
			//var usernameRegex = '/^([a-zA-Z&]+)$/';
			return value.match(/^([a-zA-Z\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only characters.',
		errorMessageKey: 'badEvenNumber'
	});

	$.formUtils.addValidator({
		name : 'PhoneNumberValid',
		validatorFunction : function(value, $el, config, language, $form) {
			return value.match(/^([0-9-()\s]+)$/);
		},
		errorMessage : 'The answer you gave must contain only numbers and - or ( )',
		errorMessageKey: 'badEvenNumber'
	});

	$.validate({
	  form : '.validate-me'
	});
</script>