<section class="app-page-header">
	<h2>Parish Groups</h2>
</section>
<section class="app-body-content">

  <div class="row-fluid top-margin-15">
    <div class="span12">

      <h4 class="subhead">Manage Your Praish's Groups</h4><br>

  		<div role="grid" class="dataTables_wrapper form-inline" id="DataTables_Table_0_wrapper">

			<table class="table table-striped table-hover groups-table dataTable" id="data-table">
				<thead class="table-headers">
					<tr role="row">
						<th>Name</th>
						<th>Phone Number</th>
						<th>Email</th>
						<th>Website</th>
						<th></th>
					</tr>
				</thead>	  
				<tbody role="alert" aria-live="polite" aria-relevant="all">
				  	<? if ($this->groupsCount > 0): ?>
						<? foreach ($this->groups as $key => $group): ?>
							<tr class="odd" url="<?= $this->links('edit_group', array('group_id' => $group->objectId)) ?>">
								<td><a href="<?= $this->links('edit_group', array('group_id' => $group->objectId)) ?>"><?= $group->name ?></a></td>
								<td><?= $group->phone ?></td>
								<td><?= $group->email ?></td>
								<td><?= $group->website ?></td>
								<td><a  data-href="<?= $this->links('delete_group', array('group_id' => $group->objectId)) ?>" class="fa fa-times reject group_destroy" href="#"></a></td>
							</tr>
						<? endforeach ?>
				  	<? else: ?>
						<tr>
							<td colspan="5">We did not find and groups matching your criteria.</td>
						</tr>
				  	<? endif; ?>
				</tbody>
			</table>
	    	<div class="pagination light-theme simple-pagination">
		      	<ul>
				  	<? if ($this->familiesCount > 0): ?>
						<?= $this->pagination->display() ?>
					<? endif; ?>
		      	</ul>
	      	</div>
		</div>
    </div>
  </div>
</section>
<script>
	ajaxData = <?= json_encode($this->groups) ?>;
	$.getScript("<?= My_Core::getApplicationUri() . $this->getJs('viewgroups.js', 'groups') ?>");
</script>