<section class="app-page-header">
	<h2>Parish Calendar</h2>
</section>
<div id="calendar" class="parish-calendar fc fc-ltr">
</div>
<!--calendar-->
<div id="myModal" class="modal hide fade in calendar-modal" aria-hidden="false" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" >
  <div class="modal-header">
    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
    <h3 class="text-centered">Add Event To Calendar</h3>
  </div>
  <div class="modal-body">
    <form class="form-horizontal validate-me">
      <div class="form-group">
        <label class="modal-label">Date</label>
        <div class="modal-input">
          <input type="date" required="" value="" class="" id="eventDate">
        </div>
      </div>
      <div class="form-group">
        <label class="modal-label">Time</label>
        <div class="modal-input">
          <input type="time" placeholder="08:00" name="startDateTime" data-validation="PhoneNumberValid" data-validation-optional="true" required="" class="input-half" id="eventStartTime">
          <input type="time" placeholder="17:00" name="endDateTime" data-validation="PhoneNumberValid" data-validation-optional="true" required="" class="input-half left-margin-5" id="eventEndTime">
        </div>
      </div>
      <div class="form-group">
        <label class="modal-label">Title</label>
        <div class="modal-input">
          <input type="text" name="name" required="" placeholder="Please give your event a title" id="eventTitle">
        </div>
      </div>

      <div class="form-group">
        <label class="modal-label">Type</label>
        <div class="modal-input">
          <select name="label" id="label" required="" class="modal-select">
            <option name="service">Church Service</option>
            <option name="youthEvent">Youth Event</option>
            <option name="other">Other</option>
          </select>
        </div>
      </div>

      <div class="form-group">
        <label class="modal-label">Details</label>
          <textarea name="description" class="form-textarea" placeholder="Additional details or notes" id="message"></textarea>
      </div>
    </form>
  </div>
  <div class="modal-footer">
    <div class="modal-footer-buttons">
      <a aria-hidden="true" data-dismiss="modal" class="grey-link right-margin-10">Cancel</a>
      <button class="button button-green" id="new-event">Add Event</button>
    </div>
    <div class="modal-footer-loader hide"> 
      <div id="floatingCirclesG" class="loading-delete-families-small modal-loader"><div id="frotateG_01" class="f_circleG"></div><div id="frotateG_02" class="f_circleG"></div><div id="frotateG_03" class="f_circleG"></div><div id="frotateG_04" class="f_circleG"></div><div id="frotateG_05" class="f_circleG"></div><div id="frotateG_06" class="f_circleG"></div><div id="frotateG_07" class="f_circleG"></div><div id="frotateG_08" class="f_circleG"></div></div>
    </div>
  </div>
</div>
<!--#myModal-->

<div id="edit-event" class="modal hide fade in calendar-modal" aria-hidden="false" aria-labelledby="edit-eventLabel" role="dialog" tabindex="-1" >
  <div class="modal-header">
    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
    <h3 class="text-centered">Edit Event</h3>
  </div>
  <div class="modal-body">
    <form class="form-horizontal validate-me">
      <input type="hidden" value="" name="id" id="edit-event-id">
      <div class="form-group">
        <label class="modal-label">Date</label>
        <div class="modal-input">
          <input type="date" required="" value="" class="" id="edit-eventDate">
        </div>
      </div>
      <div class="form-group">
        <label class="modal-label">Time</label>
        <div class="modal-input">
          <input type="time" placeholder="08:00" name="startDateTime" data-validation="PhoneNumberValid" data-validation-optional="true" required="" class="input-half" id="edit-eventStartTime">
          <input type="time" placeholder="17:00" name="endDateTime" data-validation="PhoneNumberValid" data-validation-optional="true" required="" class="input-half left-margin-5" id="edit-eventEndTime">
        </div>
      </div>
      <div class="form-group">
        <label class="modal-label">Title</label>
        <div class="modal-input">
          <input type="text" name="name" required="" placeholder="Please give your event a title" id="edit-eventTitle">
        </div>
      </div>

      <div class="form-group">
        <label class="modal-label">Type</label>
        <div class="modal-input">
          <select name="label" id="edit-label" required="" class="modal-select">
            <option name="service">Church Service</option>
            <option name="youthEvent">Youth Event</option>
            <option name="other">Other</option>
          </select>
        </div>
      </div>

      <div class="form-group">
        <label class="modal-label">Details</label>
          <textarea name="description" class="form-textarea" placeholder="Additional details or notes" id="edit-message"></textarea>
      </div>
    </form>
  </div>
  <div class="modal-footer">
    <div class="modal-footer-buttons">
      <a aria-hidden="true" data-dismiss="modal" class="grey-link right-margin-10">Cancel</a>
      <button class="right-margin-10 button button-green" id="update-event">Update</button>
      <button class="button button-red" id="remove-event">Remove</button> 
    </div>
    <div class="modal-footer-loader hide"> 
      <div id="floatingCirclesG" class="loading-delete-families-small modal-loader"><div id="frotateG_01" class="f_circleG"></div><div id="frotateG_02" class="f_circleG"></div><div id="frotateG_03" class="f_circleG"></div><div id="frotateG_04" class="f_circleG"></div><div id="frotateG_05" class="f_circleG"></div><div id="frotateG_06" class="f_circleG"></div><div id="frotateG_07" class="f_circleG"></div><div id="frotateG_08" class="f_circleG"></div></div>
    </div>
  </div>
</div>
<!--#myModal-->

<script>
	var addEventUrl = "<?= $this->links('add_event') ?>",
		editEventUrl = "<?= $this->links('edit_event', array('event_id' => 0)) ?>",
		deleteEventUrl = "<?= $this->links('delete_event', array('event_id' => 0)) ?>",
		events = <?= json_encode($this->events) ?>,	eventDate, toEditEvent, toDeleteEvent,
		dateOffsetTimezone = moment().zone() * 60;
	
	for (var i = 0; i < events.length; i++) {
	 	eventStartDate = moment((events[i]['start'] - dateOffsetTimezone) * 1000);
	 	events[i]['start'] = eventStartDate.toISOString();
	 	eventEndDate = moment((events[i]['end'] - dateOffsetTimezone) * 1000);
	 	events[i]['end'] = eventEndDate.toISOString();
	}; 
	$(document).ready(function(){
		$('#calendar').fullCalendar({
			selectable: true,
			editable: true,
			timeFormat: 'H:mm',
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			events: events,
			eventDrop: function( event, delta, revertFunc, jsEvent, ui, view ) {
				console.log(event.start.format());
			},
			eventResize: function( event, jsEvent, ui, view ) {
				console.log(event.end.format());
			},
			eventClick: function(cal_event, jsEvent, view) {
				var $event_edit = $('#edit-event');
				$event_edit.find('#edit-eventTitle').val(cal_event.title);
				$event_edit.find('#edit-eventStartTime').val(cal_event.start.format("HH:mm"));
				$event_edit.find('#edit-eventEndTime').val(cal_event.end.format("HH:mm"));
				$event_edit.find('#edit-label').val(cal_event.label);
				$event_edit.find('#edit-message').val(cal_event.description);
				$event_edit.find('#edit-eventDate').val(cal_event.start.format("YYYY-MM-DD"));
				$event_edit.find('#edit-event-id').val(cal_event.id);
				$event_edit.modal('show');
				inUseEvent = cal_event;
			},

			dayClick: function(date, jsEvent, view) {
				$('#eventDate').val(date.format("YYYY-MM-DD"));
				$('#myModal').modal('show');
			}
		});
		
		// add new event
		$('#myModal').on('click', '#new-event', function() {
			$('#myModal .modal-footer-buttons').hide();
			$('#myModal .modal-footer-loader').show();
			var params = {startDateTime: $("#eventDate").val() + " " + $("#eventStartTime").val(), endDateTime: $("#eventDate").val() + " " + $("#eventEndTime").val(), name: $("#eventTitle").val(), label: $("#label").val(), description: $("#message").val()};
			$.post(addEventUrl, params, function (data){
				VanillaZF.acknowledge(data);
				if (data.success)
					$("#calendar").fullCalendar('renderEvent', {id: data.id, title: params.name, start: params.startDateTime, end: params.endDateTime, label: params.label, description: params.description}, true);
			}, 'json');
		}); 
		
		$('#edit-event').on('click', '#update-event', function() {
			$('#edit-event .modal-footer-buttons').hide();
			$('#edit-event .modal-footer-loader').show();
			var params = {startDateTime: $("#edit-eventDate").val() + " " + $("#edit-eventStartTime").val(), endDateTime: $("#edit-eventDate").val() + " " + $("#edit-eventEndTime").val(), name: $("#edit-eventTitle").val(), label: $("#edit-label").val(), description: $("#edit-message").val()};
			$.post(editEventUrl.replace(0, $("#edit-event-id").val()), params, function (data){
				VanillaZF.acknowledge(data);
				if (data.success)
				{
					inUseEvent.title = params.name;
					inUseEvent.start = params.startDateTime;
					inUseEvent.end = params.endDateTime;
					inUseEvent.label = params.label;
					inUseEvent.description = params.description;
					$('#calendar').fullCalendar('updateEvent', toEditEvent);
				}	
			}, 'json');
		});

		$('#edit-event').on('click', '#remove-event', function() {
			$('#edit-event .modal-footer-buttons').hide();
			$('#edit-event .modal-footer-loader').show();
			toDeleteEvent = $("#edit-event-id").val();
			$.post(deleteEventUrl.replace(0, $("#edit-event-id").val()), function (data){
				VanillaZF.acknowledge(data);
				if (data.success)
					$("#calendar").fullCalendar('removeEvents', toDeleteEvent);
			}, 'json');
		});

	});
	function resetModal(id)
	{
		$(id + ' .modal-footer-buttons').show();
		$(id + ' .modal-footer-loader').hide();
		$(id).modal('hide');
		jQForm = $(id + ' form');
		jQForm[0].reset();
	}

  $.formUtils.addValidator({
    name : 'PhoneNumberValid',
    validatorFunction : function(value, $el, config, language, $form) {
      return value.match(/^([0-9:\s]+)$/);
    },
    errorMessage : 'The answer you gave must contain only numbers and :',
    errorMessageKey: 'badEvenNumber'
  }); 

  $.validate({
    form : '.validate-me'
  });

</script>